<Project>
  <PropertyGroup>
    <ArtifactsPath>$(MSBuildThisFileDirectory)out</ArtifactsPath>
    <VSTestResultsDirectory Condition="'$(VSTestResultsDirectory)' == ''">$(ArtifactsPath)/test-results/$(MSBuildProjectName)</VSTestResultsDirectory>
    <CoverletOutput Condition="'$(CoverletOutput)' == ''">$(ArtifactsPath)/test-results/$(MSBuildProjectName)/</CoverletOutput>

    <!-- Read version from version -->
    <VersionFile>$(MSBuildThisFileDirectory)version</VersionFile>
    <Version>$([System.IO.File]::ReadAllText('$(VersionFile)').Trim())</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <PackageVersion>$(Version)</PackageVersion>

    <!-- Enable source link -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All"/>
  </ItemGroup>
</Project>
