<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Title>Bond IDL Parser</Title>
    <PackageId>BondTools.Parser</PackageId>
    <Authors>Mirco De Zorzi</Authors>
    <Description>A parser and compatibility checker for the Bond IDL.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <NoWarn>CS1584,CS1658,CS1591</NoWarn>
    <RootNamespace>Bond.Parser</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
    <None Include="../LICENSE" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" />
    <PackageReference Include="Antlr4BuildTasks" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Antlr4 Include="Grammar\Bond.g4">
      <Package>Bond.Parser.Grammar</Package>
      <Visitor>True</Visitor>
      <Listener>False</Listener>
    </Antlr4>
  </ItemGroup>

</Project>
