<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Bond.Parser\Bond.Parser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>

    <!-- Tool configuration -->
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>bond</ToolCommandName>
    <PackageId>bond-tools</PackageId>
    <Authors>Mirco De Zorzi</Authors>
    <Description>Bond IDL compiler and toolchain</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <RootNamespace>Bond.Parser.CLI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
    <None Include="../LICENSE" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
